# For more information visit: https://laravel.com/docs/sail
version: '3'
services:
    mc-laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${REVERB_PORT:-6174}:${REVERB_PORT:-6174}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - mc
        depends_on:
            - mc-mysql
            - mc-redis
            - mc-meilisearch
            - mc-rabbitmq
    mc-mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mc-mysql:/var/lib/mysql:delegated'
        networks:
            - mc
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    mc-phpmyadmin:
        image: 'phpmyadmin:5.2.1'
        ports:
            - '8080:80'
        networks:
            - mc
        links:
            - mc-mysql
        depends_on:
            - mc-mysql
        environment:
            - PMA_ARBITRARY=1
    mc-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'mc-redis:/data'
        networks:
            - mc
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
    mc-meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'mc-meilisearch:/data.ms'
        networks:
            - mc
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
            retries: 3
            timeout: 5s
    mc-rabbitmq:
        image: 'rabbitmq:3-management-alpine'
        ports:
            - '5672:5672' # RabbitMQ default port for messaging
            - '15672:15672' # RabbitMQ management UI
        volumes:
            - 'mc-rabbitmq:/var/lib/rabbitmq'
        networks:
            - mc
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASS}'
        healthcheck:
            test: [ "CMD", "rabbitmqctl", "status" ]
            interval: 30s
            timeout: 10s
            retries: 3
    mc-mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - mc
networks:
    mc:
        driver: bridge
volumes:
    mc-rabbitmq:
        driver: local
    mc-meilisearch:
        driver: local
    mc-redis:
        driver: local
    mc-mysql:
        driver: local
